### ISSUE TITLE
Following README for DirectorLoop results in NotImplementedError

### ISSUE THREAD

**Issue by krummja** [irskep/clubsandwich#24]
Hello! I have been using BLT for my roguelike project, and I wanted to give ClubSandwich a try. I was replacing some of my existing code with the examples used in the README, and maybe I'm doing something wrong, but I wanted to see what was up with this.

Here is what I have in my code:

```python
class MainMenuScene(Scene):

    def terminal_update(self, is_active=False):
        print(0, 0, "Press Enter to begin the game, ESC to quit.")

    def terminal_read(self, val):
        if val == terminal.TK_ENTER:
            self.director.push_scene(GameScene())
        elif val == terminal.TK_ESCAPE:
            self.director.pop_scene()


class GameScene(Scene):
    def terminal_update(self, is_active):
        return super().terminal_update(is_active=is_active)

    def terminal_read(self, char):
        return super().terminal_read(char)


class Director(DirectorLoop):
    def get_initial_scene(self):
        return MainMenuScene()
```

On extended `DirectorLoop`, making a `MainMenuScene` subclass of `Scene`, and attempting to run it, instead of the expected behavior I get a `NotImplementedError` being raised. Here's the traceback:

```
Traceback (most recent call last):
  File "./anathema/main.py", line 12, in <module>
    main()
  File "./anathema/main.py", line 8, in main
    game.start()
  File "/home/krummja/Workspace/Python/Anathema/anathema/core/game.py", line 89, in start
    self.loop()
  File "/home/krummja/Workspace/Python/Anathema/anathema/core/game.py", line 106, in loop
    DirectorLoop().run()
  File "/home/krummja/Workspace/Python/Repositories/src/clubsandwich/clubsandwich/blt/loop.py", line 77, in run
    self.terminal_init()
  File "/home/krummja/Workspace/Python/Repositories/src/clubsandwich/clubsandwich/director.py", line 165, in terminal_init
    self.replace_scene(self.get_initial_scene())
  File "/home/krummja/Workspace/Python/Repositories/src/clubsandwich/clubsandwich/director.py", line 153, in get_initial_scene
    raise NotImplementedError()
NotImplementedError
```

Let me know if you need any other information, and I'm happy to provide it. If I'm missing something obvious, of course, please do let me know as well!

**Comment by irskep** [comment]
It was because you were trying to use the base DirectorLoop class instead of your own Director subclass.
